### ISSUE TITLE
Gradle problem

### ISSUE THREAD

**Issue by FunnyDevs** [adrielcafe/AndroidStreamable#1]
Hi! I'm trying to add your library, but i have found this error from Android Studio

Failed to resolve: com.github.adrielcafe:AndroidStreamable:0.2

**Comment by adrielcafe** [comment]
Hi @FunnyDevs!

Have you added this snippet on your app/build.gradle?

```
repositories {
  maven {
    url "https://jitpack.io"
  }
}
```

**Comment by FunnyDevs** [comment]
Yes. I have tried with AndroidStreamable:0.1 and it works

**Comment by adrielcafe** [comment]
Yeah, really has a problem with this release, JitPack can't build this (don't know why) and the [log genereted](https://jitpack.io/com/github/adrielcafe/AndroidStreamable/0.2/build.log) by him don't says too much.

Release **0.3** is out. I've tested and is ok.

```
compile 'com.github.adrielcafe:AndroidStreamable:0.3@aar'
```

I apologize for this inconvenience :(
